export default interface ParentGuardianInterface{
    parent_guardian_id: number,
    mother_first_name: string,
    mother_middle_name: string,
    mother_last_name: string,
    mother_contact_no: string,
    father_first_name: string,
    father_middle_name: string,
    father_last_name: string,
    father_contact_no: string,
    guardian_first_name: string,
    guardian_middle_name: string,
    guardian_last_name: string,
    guardian_contact_no: string,
}